### PR TITLE
0.4 compat

### PR DESCRIPTION
**Pull request by tmlbl**
Tested in 0.3 and 0.4. Used a `typealias` to only make one reference to `@compat`.

### CODE REVIEW

**Comment by tmlbl** [comment]
Not sure why this failed on Travis, as it runs on `0.3.9` for me.

**Comment by pzion** [comment]
I'm not very familiar with the intricacies of Julia syntax, but is it possible that the Obj(x=>y, ...) constructions should be Dict(x=>y, ...) instead?  That seems to be used elsewhere...

**Comment by tmlbl** [comment]
The suggested syntax for 0.4 is `Dict{Any,Any}(x => y)`, the statement I added:
```julia
typealias Obj @compat Dict{Any,Any}
```
Provides the `Obj()` shortcut, which should function the same as `Dict()`

**Comment by tmlbl** [comment]
I am at a loss. Can't seem to get around this Travis error. Works fine on my box:

```
julia> versioninfo()
Julia Version 0.3.10
Commit c8ceeef* (2015-06-24 13:54 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.test("LibBSON", coverage=true)
INFO: Computing test dependencies for LibBSON...
INFO: No packages to install, update or remove
INFO: Testing LibBSON
Warning: could not import Base.dict into LibBSON
BSONOID
5 facts verified.
BSONObject
     - BSONObject with OID
     - BSONObject from JSON
     - BSONObject containing BSONObject
11 facts verified.
BSONArray
5 facts verified.
BSONObject: get!
3 facts verified.
INFO: LibBSON tests passed
INFO: No packages to install, update or remove

```

**Comment by pzion** [comment]
Yes, this is bizarre — I will try to take a look tonight on my end to see if I can see what’s going on…

**Comment by tmlbl** [comment]
Apparently my `typealias` was not working. I had done something similar on another project, but I don't know what is different here. Going back to using `@compat` everywhere worked. Let me know if any other parts can use cleaning up.

**Comment by pzion** [comment]
Thanks!

**Pull request merged**
