### PR TITLE
Including the binary type in the BSONObject structure.

### PR DESCRIPTION
**Pull request by GearsAD**
Hi PZion,

We included the binary data type for our testing and thought we would check if you would like to merge these changes upstream. Please let us know if you would like any additions or modifications.

Thanks,
Sam

### CODE REVIEW

**Comment by dehann** [comment]
Hi,

The test failure might be a upstream v0.6 change in deps.jl usage (from Travis v0.6):

```julia
INFO: Testing LibBSON
WARNING: deprecated syntax "abstract Result" at /home/travis/.julia/v0.6/FactCheck/src/FactCheck.jl:46.
Use "abstract type Result end" instead.
ERROR: LoadError: LoadError: could not open file /home/travis/.julia/v0.6/LibBSON/src/../deps/deps.jl
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:539
while loading /home/travis/.julia/v0.6/LibBSON/src/LibBSON.jl, in expression starting on line 5
while loading /home/travis/.julia/v0.6/LibBSON/test/runtests.jl, in expression starting on line 1
===============================[ ERROR: LibBSON ]===============================
failed process: Process(`/home/travis/julia/bin/julia -Cx86-64 -J/home/travis/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=user --color=no --compilecache=yes /home/travis/.julia/v0.6/LibBSON/test/runtests.jl`, ProcessExited(1)) [1]
================================================================================
```
Maybe we should ignore build status on nightly builds for now? I use these lines in my ```.travis.yml``` file to ignore:
```travis
matrix:
  allow_failures:
    - julia: nightly
```

**Comment by dehann** [comment]
Hi @pzion , any thoughts?

**Comment by pzion** [comment]
@dehann Sorry, we just had a baby -- no joke!  I will take a look early next week.

**Comment by dehann** [comment]
Congratulations! Thanks.

**Comment by pzion** [comment]
Just looking at this now.  You are right -- it's an upstream change in julia nightlies and has nothing to do with your code, so I will just disable the tests against nightlies for now.

**Comment by dehann** [comment]
Great, thanks!

**Comment by GearsAD** [comment]
@pzion Congrats with the baby, and thanks for the merge!

**Pull request merged**
